# Generated by Django 3.2.25 on 2024-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_alter_utilisateur_options_modereglement_code_journal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='incompatibilites',
            field=models.ManyToManyField(blank=True, related_name='_core_unite_incompatibilites_+', to='core.Unite', verbose_name='Incompatibilités'),
        ),
    ]
