# Generated by Django 3.2.25 on 2024-10-02 09:15

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_alter_unite_incompatibilites'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='blocage_impayes_off',
            field=models.BooleanField(default=False, help_text="En cochant cette case, vous permettez à cette famille d'accéder aux réservations du portail même s'il y a des impayés et que le paramètre 'blocage si impayés' a été activé dans les paramètres généraux du portail.", verbose_name='Ne jamais appliquer le blocage des réservations si impayés'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_actif',
            field=models.BooleanField(default=True, verbose_name='Compte internet activé'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internet_categori', to='core.categoriecompteinternet', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_identifiant',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True, verbose_name='Identifiant')),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_mdp',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True, verbose_name='Mot de passe')),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_reservations',
            field=models.BooleanField(default=True, verbose_name='Autoriser les réservations sur le portail'),
        ),
        migrations.AddField(
            model_name='individu',
            name='internet_secquest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Question'),
        ),
    ]
